version: '3'
services:
  mongo: 
    container_name: mongo
    image: mongo
    ports: 
    - '27017:27017'
  go_ecommerce:
    build: 8000:8000
    networks:
      - deploy_network
    image: go_ecommerce
    container_name: go_ecommerce

networks:
  deploy_network:
    driver: bridge
